services:
  # extract:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - default
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RPC_USER}
      RABBITMQ_DEFAULT_PASS: ${RPC_PASSWORD}
#     networks:
#       - default

# networks:
#   default:
#     driver: bridge

